# Generated by Django 4.2.9 on 2024-01-26 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="responsable",
            field=models.CharField(default="David V.", max_length=100),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="tipo",
            field=models.CharField(default="Interno", max_length=20),
        ),
        migrations.AddField(
            model_name="tarea",
            name="fecha_asignacion",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 1, 26, 22, 14, 19, 922668, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="tarea",
            name="fecha_entrega",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 1, 26, 22, 14, 19, 923028, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="tarea",
            name="fecha_limite",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 1, 26, 22, 14, 19, 923010, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="tarea", name="prioridad", field=models.IntegerField(default=0),
        ),
    ]
