# Generated by Django 4.2.9 on 2024-01-30 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_proyecto_responsable_proyecto_tipo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarea",
            name="fecha_asignacion",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 1, 30, 3, 33, 19, 877836, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="tarea",
            name="fecha_entrega",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 1, 30, 3, 33, 19, 878252, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="tarea",
            name="fecha_limite",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 1, 30, 3, 33, 19, 878224, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
