# Generated by Django 4.2.9 on 2024-02-07 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_tarea_fecha_asignacion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarea",
            name="fecha_asignacion",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 2, 7, 0, 55, 9, 440921, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="tarea",
            name="fecha_entrega",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 2, 7, 0, 55, 9, 441392, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="tarea",
            name="fecha_limite",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 2, 7, 0, 55, 9, 441362, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
